### ISSUE TITLE
DevDeps cannot be overwritten

### ISSUE THREAD

**Issue by volkanunsal** [AminFazlMondo/Lerna-Projen#189]
Would be great to add `devDeps` using the api method rather than [overwriting the options](https://github.com/AminFazlMondo/Lerna-Projen/blob/main/src/index.ts#L50). This prevents me from passing additional dependencies to the class.

**Comment by AminFazlMondo** [comment]
Thanks @volkanunsal for raising the issue. Could you please the pull request for the fix is addressing your concern?
