### ISSUE TITLE
Support having workspaces in package.json

### ISSUE THREAD

**Issue by Hi-Fi** [AminFazlMondo/Lerna-Projen#255]
Currently construct writes the workspace information to `lerna.json` that works but doesn't allow e.g. typedoc creation from whole repo at once (see https://typedoc.org/guides/monorepo/ and TypeStrong/typedoc#2071).

If using escape hatches and adding workspace information to package JSON, output throws warning:
```
lerna WARN EWORKSPACES Workspaces exist in the root package.json, but Lerna is not configured to use them.
lerna WARN EWORKSPACES To fix this and have Lerna use workspaces to resolve packages, set `useWorkspaces: true` in lerna.json.
```

Currently there's no direct way (except escape hatches) to add that info to `lerna.json`, but it probably could be flag so that packages are not put to config but just `useWorkspaces: true`.

**Comment by AminFazlMondo** [comment]
I think that is a good idea
