### ISSUE TITLE
useWorkspaces: true creates packages entry in package.json instead of "workspaces"

### ISSUE THREAD

**Issue by nanookmetaal** [AminFazlMondo/Lerna-Projen#522]
When setting the "useWorskpaces:true" in projenrc.ts file, a list of packages is defined in package.json under the "packages" scope.

I suspect that the scope should actually be named "workspaces" for npm to recognize it as a list of valid workspaces and perform things like dependency deduping.

Am I looking at this correctly or am I missing something?

**Comment by AminFazlMondo** [comment]
I am looking into that ans investigating if this will have any affects to the older version of lerna
